apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: output-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: llama2-pod
spec:
  containers:
    - name: llama2-container
      image: jmendoza9/llama2-app:latest
      env:
        - name: MODEL
          value: "stories15M.bin" # change to any of the pretrained models used in the README.md
      command: ["/bin/sh", "-c"]
      args: ["wget https://huggingface.co/karpathy/tinyllamas/resolve/main/$MODEL && make run && ./run $MODEL > /mnt/output.log 2>&1; sleep infinity"] # modify as needed
      volumeMounts:
        - name: output-volume
          mountPath: /mnt
  volumes:
    - name: output-volume
      persistentVolumeClaim:
        claimName: output-pvc
      